apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ai-trip-planner
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/ai-trip-planner
        ports:
        - containerPort: 8080
        env:
        - name: GOOGLE_CLOUD_PROJECT
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace